version: '3'

services:

  server:
    build:
      context: ./server
    container_name: server
    networks:
      - nodenet
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && npm start"
    volumes:
      - ./server:/usr/src/app
    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - nodenet
    depends_on:
      - server

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge